[package]
name = "noid-netd"
version = "0.2.27"
edition = "2021"

[[bin]]
name = "noid-netd"
path = "src/main.rs"

[dependencies]
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
